version: '3'

services:

  fc3-keycloak:
    image: quay.io/keycloak/keycloak:21.1
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://fc3-keycloak-db:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    depends_on:
      fc3-keycloak-db:
        condition: service_healthy
  
  fc3-keycloak-db:
    image: mysql:8.0.30-debian
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
    # desabilitar restrições de segurança do mysql, pois tem uma imcopatibilidade na execução do container
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5